---
- name: SMH360 Using Azure collection
  hosts: localhost

  tasks:
    - name: Creation du RG
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"