---
- name: SMH360 Using Azure collection
  hosts: localhost

  tasks:
    - azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - azure.azcollection.azure_rm_mysqlserver:      
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: "5.7"
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200

    - azure.azcollection.azure_rm_resource:      
        api_version: '2017-12-01'
        resource_group: "{{ resource_group }}"
        provider: dbformysql
        resource_type: servers
        resource_name: "{{ mysqlserver_name }}"
        subresource:
          - type: firewallrules
            name: externalaccess
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "255.255.255.255"
    
    - azure.azcollection.azure_rm_mysqldatabase:      
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"
    
    - azure.azcollection.azure_rm_webapp:      
        resource_group: "{{ resource_group }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ app_plan_name }}"
          is_linux: false
          sku: S2
          number_of_workers: 1
        app_settings:
          SPRING_DATASOURCE_USERNAME: "{{ admin_username }}"@"{{ mysqlserver_name }}"
          SPRING_DATASOURCE_PASSWORD: "{{ admin_password }}"
          SPRING_DATASOURCE_URL: jdbc:mysql://"{{ mysqlserver_name }}".mysql.database.azure.com:3306/hotel_coupon?useSSL=true&requireSSL=false
        frameworks:
          - name: "java"
            version: "1.8"
            settings:
              java_container: tomcat
              java_container_version: "9.0"
    
