name: Deploiement SmartHotel360

on:
  push:
    branches:
      - dev

env:
  AZURE_RG: RG-Smart-Hotel
  AZURE_LOCATION: westeurope
  

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Azure Login
        uses: Azure/login@v1
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Recuperation des sources - Git
        uses: actions/checkout@v2    

      - name: Installation Module Azure pour Ansible
        run: |
          wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          pip3 install -r requirements-azure.txt
          ansible-galaxy collection install azure.azcollection

      - name: Execution du plabook Ansible
        run: |    
          ansible-playbook ./ansible/main.yml --extra-vars "resource_group=${{ env.AZURE_RG }} location=${{ env.AZURE_LOCATION }}"

             