name: Deploiement SmartHotel360

on:
  push:
    branches:
      - dev

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check version
        run: |
          wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          ls -lisa