name: Deploiement SmartHotel360

on:
  push:
    branches:
      - dev

env:
  AZURE_RG: RG-Smart-Hotel
  AZURE_LOCATION: westeurope
  AZURE_PLAN_NAME: smh360plan
  #AZURE_WEB_APP_NAME: smh360webd4040cc

jobs:
  build-Application:
    runs-on: ubuntu-latest

    steps:
      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Creation du package ROOT.war avec Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copie des artefacts
        run: mkdir staging && cp target/*.war staging

      - name: Publication des artefacts  
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging

  deploy-IaC:
    runs-on: ubuntu-latest
    needs: build-Application

    steps:
      - name: Azure Login
        uses: Azure/login@v1
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Recuperation des sources - Git
        uses: actions/checkout@v2    

      - name: Installation Module Azure pour Ansible
        run: |
          wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          pip3 install -r requirements-azure.txt
          ansible-galaxy collection install azure.azcollection

      - name: Execution du plabook Ansible
        run: |    
          ansible-playbook ./ansible/main.yml --extra-vars "resource_group=${{ env.AZURE_RG }} location=${{ env.AZURE_LOCATION }} webapp_name=${{ secrets.AZURE_WEB_APP_NAME }} app_plan_name=${{ env.AZURE_PLAN_NAME }} mysqlserver_name=${{ secrets.AZURE_DB_SERVER }} admin_username=${{ secrets.AZURE_DB_ADMIN }} admin_password=${{ secrets.AZURE_DB_PW }} mysqldb_name=${{ secrets.AZURE_DB_NAME }}"
  
  deploy-Application:
    runs-on: ubuntu-latest
    needs: deploy-IaC

    steps:
      - name: Creation dossier Artifact
        run: |
          mkdir staging

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Package
          path: staging/

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: staging/

      - name: Azure Login
        uses: Azure/login@v1
        with:    
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: Deploy-to-Azure
        with:
          app-name: smh360webd4040cc
          package: ./staging/ROOT.war
