name: Test code

on: 
  push:
    branches:
      - dev-01 

jobs:
  Test:
    runs-on: ubuntu-20.04

    steps:
      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Test Ansible
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ./ansible/main.yml

      - name: Installation Module Azure pour Ansible
        run: |
          wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          pip3 install -r requirements-azure.txt
          ansible-galaxy collection install azure.azcollection

      - name: Execution du plabook Ansible
        run: |    
          ansible-playbook ./ansible/main.yml
          