name: Test Code

on: workflow_dispatch


jobs:
  Build-Application:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: test code
        uses: nvuillam/mega-linter@v4.26.1
