name: Test code

on: 
  push:
    branches:
      - dev-01

env:
  AZURE_RG: RG-Smart-Hotel
  AZURE_LOCATION: westeurope
  AZURE_WEB_APP_NAME: smh360webd4040cc 

jobs:
  Build-Application:
    runs-on: ubuntu-20.04

    steps:

      - name: Repuperation du repo
        uses: actions/checkout@v2

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Creation du package ROOT.war avec Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copie du fichier artefacts ROOT.war 
        run: mkdir warfile && cp target/*.war warfile

      - name: Publication du fichier ROOT.war en artefact  
        uses: actions/upload-artifact@v2
        with:
          name: Package-WAR
          path: warfile

      - name: Test Ansible avec 'ansible-lint'
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ./ansible/main.yml

      - name: Publication du playbook Ansible en artefact
        uses: actions/upload-artifact@v2
        with:
          name: Ansible-Playbook
          path: ansible